/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DatasetRouteImport } from './routes/$dataset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetArtistIdRouteImport } from './routes/$dataset/$artistId'

const DatasetRoute = DatasetRouteImport.update({
  id: '/$dataset',
  path: '/$dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetArtistIdRoute = DatasetArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => DatasetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$dataset': typeof DatasetRouteWithChildren
  '/$dataset/$artistId': typeof DatasetArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$dataset': typeof DatasetRouteWithChildren
  '/$dataset/$artistId': typeof DatasetArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$dataset': typeof DatasetRouteWithChildren
  '/$dataset/$artistId': typeof DatasetArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$dataset' | '/$dataset/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$dataset' | '/$dataset/$artistId'
  id: '__root__' | '/' | '/$dataset' | '/$dataset/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetRoute: typeof DatasetRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$dataset': {
      id: '/$dataset'
      path: '/$dataset'
      fullPath: '/$dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$dataset/$artistId': {
      id: '/$dataset/$artistId'
      path: '/$artistId'
      fullPath: '/$dataset/$artistId'
      preLoaderRoute: typeof DatasetArtistIdRouteImport
      parentRoute: typeof DatasetRoute
    }
  }
}

interface DatasetRouteChildren {
  DatasetArtistIdRoute: typeof DatasetArtistIdRoute
}

const DatasetRouteChildren: DatasetRouteChildren = {
  DatasetArtistIdRoute: DatasetArtistIdRoute,
}

const DatasetRouteWithChildren =
  DatasetRoute._addFileChildren(DatasetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetRoute: DatasetRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
